### ISSUE TITLE
Connecting QBitNinja with Litecoin

### ISSUE THREAD

**Issue by TJvrDev** [MetacoSA/QBitNinja#85]
I've successfully setup QBitNinja using Bitcoin Core. I am having trouble configuring with litecoin. The readme just specifies with Bitcoin Core. Is it safe to assume that i'll need to install litecoin core to use the altcoin capabilities with Litecoin? Would that also mean that if I used an altcoin that I would need to use a different component than Bitcoin Core?

**Comment by NicolasDorier** [comment]
If you want Litecoin, you need Litecoin node software. `Chain` should be `LTC`, the rest should be the same. (I have not tried it though, so let me know how it goes)

**Comment by TJvrDev** [comment]
In Litecoin Core [testnet], it shows im connecting for a transaction. My problem is using clientQBitNinja.GetBalance. The Operations.Count always return 0. The pub key it's using has 10 test coins there and its using that pub key to get the balance. but without this operations count, i'm unable to see the unspentCoins and effectively get the balance. Do you have any ideas on what I can try to make it work?

**Comment by NicolasDorier** [comment]
Please read the doc: "QBitNinja.Listener.Console.exe --Listen"

**Comment by NicolasDorier** [comment]
how do you instanciate `clientQBitNinja` ?

**Comment by TJvrDev** [comment]
QBitNinjaClient clientQBitNinja = new QBitNinjaClient(NetworkAPI, m_network);

The NetworkAPI is assigned "http://tapi.qbit.ninja/"
& m_network is assigned NBitcoin.Altcoins.Litecoin.Instance.Testnet

**Comment by NicolasDorier** [comment]
`http://tapi.qbit.ninja/` only support BTC you need your to host your own server.

**Comment by NicolasDorier** [comment]
Follow https://github.com/MetacoSA/QBitNinja#setup-the-front

**Comment by TJvrDev** [comment]
After much testing, I think the problem is how I have litecoin.conf set up. Is there anything you would recommend changing in this?

##
## litecoin.conf configuration file. Lines beginning with # are comments.
##

# IMPORTANT: do not use the daemon's wallet
disablewallet=1

datadir=/ltc

# Network-related settings:

# Run on the test network instead of the real lite network.
testnet=1

# Listening mode, enabled by default except when 'connect' is being used. Port 19335 (TestNet4)
listen=1

#
# JSON-RPC options (for controlling a running Litecoin/litecoind process)
#

# server=1 tells litecoind to accept JSON-RPC commands
server=1
# Accept public REST requests (default: 0)
rest=1
# RPC username or password is not specified, so a cookie is written to the /ltc/testnet4 directory for the CLI to use for auth

**Comment by NicolasDorier** [comment]
The timeout has nothing to do with this.  The front does not connect to RPC. I don't really know how to troubleshoot this. If you can manage to get azure logs for the front it would be good.

**Comment by TJvrDev** [comment]
It's strange but when I enabled "Application Logging" for the webapp in Azure, it started working. Even after disabling "Application Logging". My app goes through the flow and I get a Transaction Success result from

BroadcastResponse broadcastResponse = _clientQBitNinja.Broadcast(_customerTransaction).Result;

But the wallets and testnet do not reflect the transaction.
I did retrieve the web server logs from Azure, ill email them to you.

**Comment by NicolasDorier** [comment]
please do not email, just copy paste here. What is your server url?

**Comment by TJvrDev** [comment]
https://alarisbattles.azurewebsites.net

**Comment by NicolasDorier** [comment]
OK, let's try to solve it, can you try to run the front under visual studio with the same config as the website?

**Comment by TJvrDev** [comment]
I started running QBitNinja in Visual Studio with the same config as the website.

**Comment by NicolasDorier** [comment]
Any exception or anything you can notice? You have the same timeout?

**Comment by TJvrDev** [comment]
When reviewing the logs there were a few exceptions, this was one of them:

</ExceptionString><InnerException><ExceptionType>System.TimeoutException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>The client could not finish the operation within specified timeout.</Message><StackTrace>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NBitcoin.Indexer.IndexerClient.&amp;lt;GetChainChangesUntilFork&amp;gt;d__22.MoveNext()
   at NBitcoin.Indexer.ChainChangeEntryExtensions.UpdateChain(IEnumerable`1 entries, ChainBase chain)
   at QBitNinja.QBitNinjaDependencyResolver.UpdateChain()
   at QBitNinja.UpdateChainListener.&amp;lt;Listen&amp;gt;b__10_0(Object _)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireQueuedTimerCompletion(Object state)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
</StackTrace><ExceptionString>System.TimeoutException: The client could not finish the operation within specified timeout.</ExceptionString></InnerException></Exception></TraceRecord>

**Comment by NicolasDorier** [comment]
I should be able to fix that, can you send me your account storage creds by mail?

**Comment by TJvrDev** [comment]
Sent

**Comment by NicolasDorier** [comment]
@TJvrDev can you verify that your storage account and your front website reside in the same datacenter ? (region)

**Comment by TJvrDev** [comment]
It looks like the storage account resides in East US & West US. The website resides in Central. Ill get them in the same region.

**Comment by TJvrDev** [comment]
Alright I have Web App residing in East US now. I did have to create a new web app but I applied to updated PublishSettings for QBitNinja and republished it.

**Comment by TJvrDev** [comment]
The new server url is:
http://alarisbattlesapp.azurewebsites.net/

**Comment by NicolasDorier** [comment]
`storage account resides in East US & West US` a storage account can't live in two different place.
It does not seem to have resolved the issue.

I will try something.

**Comment by NicolasDorier** [comment]
Actually it solved, it, it is not timing out now.

**Comment by NicolasDorier** [comment]
It is quite slow though... Querying on an address take a while.

**Comment by NicolasDorier** [comment]
Actually timing out. It does not make sense. What is your machine specification for the front? I am wondering if the server does not get restarted because it uses too much memory or something like this. One sec, I check on my servers.

**Comment by NicolasDorier** [comment]
Ok so this is my tier for the service plan `Basic: 1 Large`

**Comment by TJvrDev** [comment]
Before it had:
100 total ACU
1.75 GB memory

Now has:
400 total ACU
7GB memory

**Comment by NicolasDorier** [comment]
It is still timing out it seems. That is super strange. Trying to replicate it as much as I can.

**Comment by NicolasDorier** [comment]
Can you get the applications logs on your server at all? Is it still this timeout?
